# Phiên bản cú pháp của Docker Compose
version: '3.8'

# Định nghĩa mạng nội bộ (Phòng họp kín)
networks:
  minicloud-network:
    driver: bridge

# Định nghĩa các Nhạc công (Services)
services:

  # 1. Nhạc công Database (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: minicloud-db-compose
    environment:
      # Đọc từ file .env (${TEN_BIEN})
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      # Lệnh kiểm tra: "Này Postgres, mày sẵn sàng chưa?"
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s        # Cứ 5 giây hỏi 1 lần
      timeout: 5s         # Chờ trả lời tối đa 5 giây
      retries: 5          # Thử 5 lần không được mới báo là "Unhealthy" (Ốm)
    ports:
      - "5432:5432"
    # Quan trọng: Tạo ổ cứng bền vững để không mất dữ liệu khi tắt
    volumes:
      # Để Docker tự quản lý volume (An toàn nhất trên WSL)
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - minicloud-network # Cho vào phòng họp
    restart: always
  
  # 2. Nhạc công API (Backend .NET)
  api:
    # container_name: minicloud-api-compose
    # Thay vì dùng image có sẵn, ta bảo nó: "Hãy tự Build từ Dockerfile ở thư mục này"
    build:
      context: .
      dockerfile: src/MiniCloudNote.API/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # MAGIC HAPPENS HERE: Host=db
      # Thay vì localhost hay host.docker.internal, ta dùng tên service "db"
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}

    volumes:
      - .:/app # Mount thư mục hiện tại vào /app trong container  
    # API phải đợi DB chạy xong mới được chạy
    depends_on:
      db:
        condition: service_healthy # Chỉ khi DB khỏe mạnh mới cho API chạy
    networks:
      - minicloud-network # Cho vào phòng họp cùng DB
    restart: always # Đổi từ on-failure sang always cho "trâu bò" hơn

# Khai báo volume ở cuối file
volumes:
  postgres_data:
