services:
  # 1. Database (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: minicloud-postgres-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: minicloud_prod_db
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - minicloud-network
    restart: always

  # 2. Redis Cache (Bắt buộc cho Hangfire)
  redis:
    image: redis:alpine
    container_name: minicloud-redis-prod
    networks:
      - minicloud-network
    restart: always

  # 3. Main Application (.NET API)
  api:
    image: thai254/minicloudnote-api:latest 
    container_name: minicloud-api-prod
    build:
      context: ./backend
      dockerfile: Dockerfile # Nó sẽ tìm Dockerfile trong folder backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Kết nối DB dùng tên service "postgres"
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=minicloud_prod_db;Username=postgres;Password=password123
      # Kết nối Redis dùng tên service "redis"
      - ConnectionStrings__RedisConnection=redis:6379
      # ports:
      #- "5000:8080" # Trong Production, ta sẽ không mở cổng trực tiếp, mà dùng Nginx làm Reverse Proxy (Tức là chỉ Nginx (cùng mạng) mới gọi được nó.)
    expose:
      - "8080"
    depends_on:
      - postgres
      - redis
    networks:
      - minicloud-network
    restart: always

  # 4. NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: minicloud-nginx
    ports:
      - "80:80" # Mở cổng 80 (Web chuẩn) ra thế giới
      - "443:443" # Mở cổng 443 (Web bảo mật) ra thế giới
    volumes:
      # Nạp cuốn sổ tay cấu hình vào cho Nginx đọc
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api # Phải đợi API dậy thì Lễ tân mới làm việc
    networks:
      - minicloud-network
    restart: always

  # 5. watchtower (TỰ ĐỘNG UPDATE DOCKER IMAGE KHI CÓ BẢN MỚI)
  watchtower:
    image: containrrr/watchtower
    container_name: minicloud-watchtower
    volumes:
      # Cho phép Watchtower điều khiển Docker của máy chủ
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Tự động xóa Image cũ cho đỡ rác máy
      - WATCHTOWER_CLEANUP=true
      # Kiểm tra cập nhật mỗi 30 giây (Mặc địch là 24h - quá lâu cho Demo)
      - WATCHTOWER_POLL_INTERVAL=30
      - DOCKER_API_VERSION=1.45
    networks:
      - minicloud-network
    restart: always

volumes:
  pgdata_prod:

networks:
  minicloud-network: